### PR TITLE
Fix: multiple events overwrite existing config

### PR DESCRIPTION
**Pull request by kotaroito**
## Problem
As #40 and #46 report, I'm having the same issue.

According to the API Reference [PUT Bucket notification](https://docs.aws.amazon.com/AmazonS3/latest/API/RESTBucketPUTnotification.html), the API replaces the existing notification configuration.

## Solution

Putting all events defined in serverless.yml.

To achieve this, removing the code that checks current S3 events might be the simplest way.
(I hope there is no blind spot...)

### CODE REVIEW

**Comment by shaunc** [comment]
Any news on this issue? ... quite annoying problem. Does this PR work?

**Comment by shaunc** [comment]
:tada: :) Thanks, @matt-filion ! (and @kotaroito for submitting, of course)

**Comment by matt-filion** [comment]
Thanks for your contribution! Sorry for the big delay in getting it all merged in.

**Comment by kotaroito** [comment]
Thank you for merging the PR,  @matt-filion !

**Pull request merged**
