### PR TITLE
Fix: fix SourceArn error when create policy(aws china)

### LINKED ISSUE #68: an issue of SourceArn error in aws-cn
when create Policy, the attribute 'SourceArn' of payload should be `arn:aws-cn:s3:::${bucketName}`, not `arn:aws:s3:::${bucketName}`

### PR DESCRIPTION
**Pull request by terrynie**
close #68

### CODE REVIEW

**Comment by terrynie** [comment]
people use aws-cn can config serverless.yml like this.
```
provider:
  name: aws
  region: cn-north-1
  ....
```

**Comment by matt-filion** [comment]
Why did the plugin itself need to be renamed, wasn't the regex configuration enough of a change to allow cn aws?

**Comment by terrynie** [comment]
sorry, it's my fault.

I will close this PR,  then fix the conflict and request a new PR

**Comment by terrynie** [comment]
I have request a new PR  #73

**Pull request closed without merging**
