### PR TITLE
fix issue with first deploy

### PR DESCRIPTION
**Pull request by rschick**
Addresses issue #38

### CODE REVIEW

**Comment by malcyL** [comment]
I've run into this issue, so I've tested with the fix on this branch. It's resolved the problem for me.

Is it possible to get this merged?

**Comment by Crow-EH** [comment]
Hi everyone.

I confirm that it fixes the `TypeError: Cannot read property 'Statement' of undefined` on `Permission.js` at the first run.

Any help required to test specific cases @rschick / @matt-filion ?

This bug is pretty anoying in continuous deployment.

**Comment by rschick** [comment]
@Crow-EH just waiting for @matt-filion to merge I think..

**Comment by matt-filion** [comment]
Merged and pushed to NPM (v.2.2.2), sincere apologies for the delay.

Thanks for the contribution @rschick !

**Comment by rschick** [comment]
Sweet, thx @matt-filion

**Comment by malcyL** [comment]
Great! Thanks, @matt-filion.

**Comment by Crow-EH** [comment]
Thanks everyone

**Pull request merged**
