### PR TITLE
Added Serverelss deploy and remove event hooks, added pre deployment …

### PR DESCRIPTION
**Pull request by julianpitt**
Features added:
 - Pre deployment check to ensure bucket exists
 - Hook into Serverless framework deploy command and attach events after successful deploy
 - Hook into Serverless framework remove command and remove events before removing the CF stack

### CODE REVIEW

**Comment by matt-filion** [comment]
Thanks for the contribution. I'll see if I can merge your changes over to 2.0, mind if I reach out for assistance if I get stuck?

**Comment by julianpitt** [comment]
No problem at all

**Comment by julianpitt** [comment]
This should close issues #22 and #29

**Comment by scottschreckengaust** [comment]
Can this get merged back into `2.0`?

**Pull request merged**
